#!/bin/bash 
# this script sets up / deploys a mean stack webapp on a server from scratch
# usage: deploy mydomain.com /path/to/repo
# backend must be under backend/server.js
# fronent must be in frontend subdir of repo

# install nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
source ~/.bashrc
nvm install --lts

source ~/.bashrc
npm config set user 0
npm config set unsafe-perm true
# echo 'n\n' | npm i @angular/cli -g
npm i pm2 -g

apt update
apt install htop
apt install nginx

echo "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root "/usr/share/"$1"/client/"; # $1 is domain name
  index index.html;

  location / {
    try_files $uri$args $uri$args/ /index.html;
  }
  
  location /api/ {
    proxy_pass http://localhost:3000;
    proxy_http_version 1.1;
  }
} " > /etc/nginx/sites-available/default
service nginx restart
source ~/.bashrc

cd $2"/frontend" # git repo directory
npm install
ng build --prod=true

cd $2
npm install

pm2 start $2"/backend/server.js"

mv $2"/frontend/dist/" "/usr/share/"$1

./update $1 $2
