#!/bin/bash 
# this script sets up / deploys a mean stack webapp on a server from scratch
# usage: deploy mydomain.com /path/to/repo

PORT=""
DOMAIN_NAME=""

sudo apt install -y curl build-essential htop

# generate ssh key
echo '\n\n\n\n\n\n'| ssh-keygen -t rsa -b 4096

#
# set as GitHub deploy key
#

source install_scripts/install_docker && install_docker
source install_scripts/nginx && install_nginx && deploy_nginx_http $PORT $DOMAIN_NAME

printf '\n# adding deploy and update scripts to $PATH\nexport PATH=$PATH:'$(eval echo "~/NR-Dashboard/scripts/") >> ~/.bashrc && source ~/.bashrc
