#!/bin/bash 
# this script sets up / deploys a mean stack webapp on a server from scratch
# usage: deploy mydomain.com /path/to/repo

PUB_SSH_KEY=~/.ssh/id_rsa.pub
if [ ! -f "$PUB_SSH_KEY" ]; then
    # generate ssh key
    echo '\n\n\n\n\n\n'| ssh-keygen -t rsa -b 4096
fi

echo "Add this to GitHub deploy keys:"
echo
cat $PUB_SSH_KEY
echo

read -p "Enter GitHub repository: " repo

git clone $repo

PORT=""
DOMAIN_NAME=""

sudo apt install -y curl build-essential htop

#
# set as GitHub deploy key
#

source install_scripts/install_docker && install_docker
source install_scripts/nginx && install_nginx && deploy_nginx_http $PORT $DOMAIN_NAME

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

printf '\n# adding deploy and update scripts to $PATH\nexport PATH=$PATH:'$SCRIPT_DIR'\n' >> ~/.bashrc && source ~/.bashrc
