#!/bin/bash 
# assumes a web server has already been deployed with ./deploy.sh
# this script deploys new changes to the already running instance

if [[ -z "$SSH_PKEY" ]]
then
    printf "\nREMEMBER TO SET ENVIRONMENT VARIABLES\n\n"
    exit
fi

