#!/bin/bash 
# assumes a web server has already been deployed with ./deploy.sh
# this script deploys new changes to the already running instance

echo "REMEMBER TO SET ENV VARIABLES"
cd $2
git pull
npm i

cd $2"/frontend"
ng build --prod=true
rm -rf "/usr/share/"$1
mv $2"/frontend/dist/" "/usr/share/"$1

pm2 delete server
pm2 start $2"/backend/server.js"
